apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-workflow-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: start
  templates:
  - name: start
    dag:
      tasks:
      - name: A # Task A has no dependency so will start automatically
        template: echo
        arguments:
          parameters: [{name: message,value: A}]
      - name: B # Task B depends on Task A
        dependencies: [A] # Task B depends on task A
        template: echo
        arguments:
          parameters: [{name: message,value: B}]
      - name: C # Task C depends on Task A
        dependencies: [A] # Task C depends on task A
        template: echo
        arguments:
          parameters: [{name: message,value: C}]
      - name: D # Task D depends on Task B and C
        dependencies: [B,C] # Task B depends on task A
        template: echo
        arguments:
          parameters: [{name: message,value: D}]
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      imagePullPolicy: IfNotPresent
      command: [echo , "The message value was: {{inputs.parameters.message}}"]

